<?php

include_once('lib/posting.class.php');

/**
 * Add page for Scheduled Reminders form.
 * 
 * Implements hook_menu().
 */
function hos_scheduler_menu() {
  $items = [];
  // Path to config form for module.
  $items['admin/config/scheduler'] = [
    'title' => 'Scheduled Reminders Settings',
    'description' => 'Module settings for Scheduled Reminders',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['hos_scheduler_config_form'],
    'access callback' => 'user_has_role',
    'access arguments' => ['3'],
  ];

  // Path to form for users to import new data.
  $items['admin/content/scheduler/import'] = [
    'title' => 'Import scheduled reminders',
    'description' => 'Form to import scheduled reminders and create SMS posts',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['hos_scheduler_form'],
    'access callback' => TRUE,
    // Add the relevant user role here.
    // 'access arguments' => ['x'],
  ];

  return $items;
}

/**
 * Create module config form.
 * 
 * Implements hook_form().
 */
function hos_scheduler_config_form($form, &$form_state) {
  // Get value from database.
  $message_text = variable_get('hos_scheduler_message', '');

  $form['message'] = [
    '#type' => 'html_tag',
    '#tag' => 'p',
    '#value' => t('All reminder messages will be sent with the following text. Users can enter a custom text for a batch of messages when the batch is created.'),
  ];

  $form['message_text'] = [
    '#title' => t('Text of Scheduled Reminder Messages'),
    '#description' => t("Enter message text. Use the placeholders '\$date' and '\$provider' to insert the relevant text in the message. <br />Remember this is SMS, so characters are limited. Character count is limited to 120."),
    '#type' => 'textarea',
    '#default_value' => $message_text,
  ];

  $form['message_count'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['active-message-count']
    ]
  ];

  $form['message_count']['label'] = [
    '#type' => 'html_tag',
    '#tag' => 'span',
    '#value' => t('Character count: '),
  ];

  $form['message_count']['count'] = [
    '#type' => 'html_tag',
    '#tag' => 'span',
    '#value' => strlen($message_text),
    '#attributes' => [
      'id' => 'activeCharCount'
    ],
  ];

  $form['submit_button'] = [
    '#type' => 'submit',
    '#value' => t('Save'),
  ];

  // Add js on this page only.
  // JS providers dynamic character count.
  $module_path = drupal_get_path('module', 'hos_scheduler');
  drupal_add_js($module_path . '/js/scheduler.js', ['scope' => 'footer']);

  return $form;
}

/**
 * Implements hook_form_validate().
 */
function hos_scheduler_config_form_validate($form, &$form_state) {
  // Limit all messages to a character count?
  $text = trim($form['message_text']['#value']);

  if (strlen($text) >= 120) {
    form_set_error('message_text', 'The message is too long! Please limit to 120 characters.');
  }
}

/**
 * Implements hook_form_submit().
 */
function hos_scheduler_config_form_submit($form, &$form_state) {
  $text = trim($form['message_text']['#value']);

  // Store new message to database.
  variable_set('hos_scheduler_message', $text);
  // Show confirmation message.
  drupal_set_message('Message text is saved', 'status');
}

/**
 * Create Scheduled Reminders form.
 * 
 * Implements hook_form().
 */
function hos_scheduler_form($form, &$form_state) {
  // Text of outgoing messages.
  // Get global value from database.
  $message_text = variable_get('hos_scheduler_message', '');

  // Outgoing message text.
  $form['message_text'] = [
    '#type' => 'container'
  ];

  $form['message_text']['label'] = [
    '#type' => 'html_tag',
    '#tag' => 'p',
    '#value' => t('Each message will have the following text:'),
  ];

  // Display current value in database.
  $form['message_text']['global_text'] = [
    '#type' => 'html_tag',
    '#tag' => 'p',
    '#value' => $message_text,
    '#prefix' => '<em>',
    '#suffix' => '</em>',
  ];

  $form['message_text']['custom_text'] = [
    '#type' => 'fieldset',
    '#title' => t('Custom message text'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  ];

  // Form for custom outgoing message text for current batch.
  $form['message_text']['custom_text']['custom_form'] = [
    '#title' => t('Message text'),
    '#description' => t('Each message willl contain this text, along with the provider name, and event date.'),
    '#type' => 'textarea',
    '#default_value' => '',
  ];

  // CSV data input elements.
  $form['text_input'] = [
    '#title' => t('CSV-type Data'),
    '#description' => t('Paste CSV-style data to create reminders. The first line must contain column headers in order to properly match data. 
      Each entry must be on a new line.<br />
      Dates should be formatted as 2017-07-07 12:15.'),
    '#type' => 'textarea',
    '#default_value' => '',
    '#required' => TRUE,
  ];

  $form['data_separator'] = [
    '#title' => t('Data separator'),
    '#description' => t('Indicate whether data on each line is separated by a comma (,) or a pipe (|)'),
    '#type' => 'select',
    '#options' => [
      ',' => 'Commas',
      '|' => 'Pipes'
    ],
    '#empty_option' => '--Select a value--',
    '#required' => TRUE,
  ];

  $form['submit_button'] = [
    '#type' => 'submit',
    '#value' => t('Submit'),
  ];
  
  return $form;
}

/**
 * Implements hook_form_validate().
 */
function hos_scheduler_form_validate($form, &$form_state) {
  // Get form values.
  $textData = $form['text_input']['#value'];
  $csvSeparator = $form['data_separator']['#value'];
  
  // Verify that data headers have relevant column names, i.e. phone, date.
  $dataRows = str_getcsv($textData, "\n");
  // Get column titles only.
  $headers = explode($csvSeparator, $dataRows[0]);

  // Validate for more than one row.
  if (count($dataRows) <= 1) {
    form_set_error('text_input', "Could not read the CSV data. Make sure each entry is contained on a separate line, and the column titles are included on the first line.");
    return;
  }
  
  // Cleanse data.
  $headers = array_map('trim', $headers);
  $headers = array_map('strtolower', $headers);

  // First row of data should contain column titles, i.e. phone, name.
  if ( !in_array('phone', $headers) ||
       !in_array('name',  $headers) ||
       !in_array('date',  $headers) ) {
    form_set_error('text_input', 'Data must contain column headers which include: phone, name, date.');
  }
}

/**
 * Implements hook_form_submit().
 */
function hos_scheduler_form_submit($form, &$form_state) {
  // Get CSV data and separator.
  $results = _hos_scheduler_read_csv($form['text_input']['#value'], $form['data_separator']['#value']);

  // Get message text from global setting, or custom message for current batch.
  $custom_message = trim($form['message_text']['custom_text']['custom_form']['#value']);
  if ($custom_message == '') {
    $message_text = variable_get('hos_scheduler_message', '');
  }
  else {
    $message_text = $custom_message;
  }

  // Collection for current batch of new messages.
  $new_messages = [];

  foreach($results as $result) {
    // Create new posting object.
    $message = new Posting($result);
    // Add message body.
    $message->addBody($message_text);
    // Add to collection.
    $new_messages[] = $message;
  }
  
  // Do something with collection, i.e. create nodes.
  foreach($new_messages as $node) {
    drupal_set_message($node->speak());
    // dpm($node);
  }

  // If successful, take to content page.
  // $form_state['redirect'] = '/';
}

/**
 * Helper function to read CSV-style data
 * 
 * @param string $rawData Raw data from file or formfield to be read.
 * 
 * @param string $separator Separator to use in identifying data elements, i.e. commas or pipes.
 * 
 * @return array StdClass objects of data items.
 */
function _hos_scheduler_read_csv($rawData, $separator) {
  $results = [];
  // Arbitrary counter to read header row first.
  $rowNumber = 1;
  $headers = [];

  // Import raw string as CSV.
  // Split into rows.
  $dataRows = str_getcsv($rawData, "\n");
  // Read each row.
  foreach($dataRows as $row) {
    // Read header row.
    if($rowNumber == 1) {
      // Split into cells.
      $cells = str_getcsv($row, $separator);
      foreach($cells as $cell) {
        $headers[] = $cell;
      }
      $rowNumber++;
    }
    // For data rows.
    else {
      // Create item as stdClass object.
      $object = new stdClass();
      // Split into cells.
      $cells = str_getcsv($row, $separator);
      foreach($cells as $k => $cell) {
        // Use header as property name.
        $property = $headers[$k];
        $object->$property = $cell;
      }

      $results[] = $object;
    }
  }

  return $results;
}